trigger:
  - none

pr:
  - none

variables:
  - name: deploymentRegion
    value: canadacentral
  - name: serviceConnection
    value: AzMinLab-CanadaPubSecALZ
  - name: vmWinImage
    value: windows-latest
  - name: vmImage
    value: ubuntu-latest
  - name: deployOperation
    value: create
  - name: var-bashPostInjectScript
    value: ':'
  - name: var-bashPreInjectScript
    value: 'set -E; function catch { echo "##vso[task.logissue type=error]Caller: $(caller), LineNo: $LINENO, Command: $BASH_COMMAND" ; exit 1 ; } ; echo ; echo "Current working directory: $(pwd)" ; echo ; trap catch ERR'
  - name: avdShrdlSubsId
    value: f013bc3f-1407-4b68-a977-9f22ef438677
  - name: avdWrklSubsId
    value: f013bc3f-1407-4b68-a977-9f22ef438677
  - name: avdWrklSecretAccess
    value: f013bc3f-1407-4b68-a977-9f22ef438677
  - name: createAvdVnet
    value: false
  - name: useSharedImage
    value: false
  - name: avdOsImage
    #value: win11_21h2_office
    #value: win10_21h2
    value: win10_21h2_office
    #value: win11_21h2
  - name: avdIdentityDomainName
    value: azurelab.ca
  - name: avdDomainJoinUserName
    value: 'azadmin@azurelab.ca'
  - name: avdDomainJoinUserPassword
    value: '!V0ipc@123'
  - name: avdVmLocalUserName
    value: azadmin
  - name: avdVmLocalUserPassword
    value: '!R37fallacy1505'


stages:
  - stage: Deploy_AVD_Accelerator
    displayName: Deploy AVD Accelerator
    jobs:
      # Deploy template deploy-baseline.bicep for AVD Accelerator
      - template: deploy-template-sub.yml
        parameters:
          jobName: Deploy_AVD_Accelerator
          location: $(deploymentRegion)
          workingDir: $(System.DefaultWorkingDirectory)/workload/bicep
          templateFile: deploy-baseline.bicep
          parameterArray:
            - deploymentPrefix 'app1'
            - avdDeploySessionHostsCount 1
            - avdWorkloadSubsId $(avdWrklSubsId)
            - avdEnterpriseAppObjectId '82205950-fef1-4f88-8801-86e60c2e9318'
            - avdManagementPlaneLocation $(deploymentRegion)
            - avdSessionHostLocation $(deploymentRegion)
            - fslogixStorageSku 'Standard_LRS'
            - createAvdFslogixDeployment true 
        #    - avdWrklSecretAccess $(avdWrklSecretAccess)
            - existingVnetSubnetResourceId '/subscriptions/f013bc3f-1407-4b68-a977-9f22ef438677/resourceGroups/rg-avd-networking/providers/Microsoft.Network/virtualNetworks/avd-cacn-vnet/subnets/subnet1'
            - existingHubVnetResourceId '/subscriptions/f013bc3f-1407-4b68-a977-9f22ef438677/resourceGroups/rg-hub-networking/providers/Microsoft.Network/virtualNetworks/hub-vnet'
            - useSharedImage $(useSharedImage)
            - avdOsImage $(avdOsImage)
            - createAvdVnet $(createAvdVnet)
            - avdIdentityDomainName $(avdIdentityDomainName)
            - avdDomainJoinUserName $(avdDomainJoinUserName)
            - avdDomainJoinUserPassword $(avdDomainJoinUserPassword)
            - avdVmLocalUserName $(avdVmLocalUserName)
            - avdVmLocalUserPassword $(avdVmLocalUserPassword)
            - avdDeployRappGroup true
            - avdDeploySessionHosts true
            - avdStartVmOnConnect true
            - createStartVmOnConnectCustomRole true
            - vNetworkGatewayOnHub false
            - createOuForStorage true
            - storageOuName 'FsLogix User Profiles'
